name: Actions

on: [push, pull_request]

jobs:
  First-Action-Command:
    runs-on: ubuntu-latest
    steps:
      - name: Working directory
        run: |
          pwd
          ls -larth
          date
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v3
      - name: Working directory after checkout
        run: |
          date
          cd .github
          cd workflows
          ls -larth
          pwd
          echo $GITHUB_SHA             
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
        #    git clone git@github:$GITHUB_REPOSITORY
        #    git checkout $GITHUB_SHA
      ##Above is the 1.Commit ID env variable, 2. Github Repo, 3. Workspace 4.Reference of the
      - name: Simple Action
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "King Don is the Man" ##This is the output
      - name: Log greeting time
        run: echo "${{steps.greeting.outputs.time}}" ##Refrencing the Id of the above
