name: Actions

on: [push]

jobs:
  First-Action-Command:
    runs-on: ubuntu-latest
    steps:
      - name: Working directory
        run: |
          pwd
          ls -larth
          date
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v3
      - name: Working directory after checkout
        run: |
          pwd
          ls -larth
          date

      - name: Simple Action
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "King Don is the Man" ##This is the output
      - name: Log greeting time
        run: echo "${{steps.greeting.outputs.time}}" ##Refrencing the Id of the above
